import goslate

gs = goslate.Goslate()

def lerMensagem():
    arq = open("mensagem.txt","r")

    linhas = arq.readlines()

    contPalavras = str(linhas).split()
    frequencia = []
    
    for p in contPalavras:
        frequencia.append(contPalavras.count(p))
    
    print("Mensagem cifrada:\n" + str(linhas) +"\n")
    print("Contagem:\n" + str(zip(contPalavras, frequencia)))

lerMensagem()
def decriptar(k,m):
    aux = ""
    for letra in m:
        aux = aux + k[letra]
    return aux

def montarDicionario(gama1,gama2):
    if len(gama1)!=len(gama2):
        return {}
    else:
        dicionario = {}
        z = zip(gama1,gama2)
        for (x,y) in z:
            dicionario[y] = x
        return dicionario
   
chave = montarDicionario("ABCDEFGHIKLMNPORSTYUWV,123456789-. ",
                         "ULHMINJFVWGXPBTZYQEADS,123456789-. ")    


print decriptar(chave,"QFI IPVJXU HVBFIZ XUHFVPI DUY VPSIPQIM LE U JIZXUP IPJVPIIZ, UZQFAZ YHFIZLVAY, DFT UBBGVIM NTZ FVY BUQIPQ TP NILZAUZE 23, 1918. QFVY DUY VP QFI YUXI QVXI NZUXI QFUQ 3 TQFIZ VPSIPQTZY NZTX 3 TQFIZ HTAPQZVIY UGYT UBBGVIM NTZ U BUQIPQ NTZ U ZTQUZE HVBFIZ XUHFVPI. YHFIZLVAY NVZYQ QZVIM QT YIGG FVY MIYVJP QT QFI JIZXUP XVGVQUZE LAQ NVPMVPJ PT VPQIZIYQ MIHVMIM QT YQUZQ AB FVY TDP HTXBUPE QT XUPANUHQAZI QFI IPVJXU NTZ HTXXIZHVUG YUGI. QFI IPVJXU XUHFVPI DUY NVZYQ TNNIZIM NTZ YUGI VP 1923, LAQ FUM NID QUWIZY. QFI IPVJXU XUHFVPI DUY UP VPJIPVTAY UMSUPHI VP QIHFPTGTJE, LTQF NTZ QFI YQZIPJQF TN QFI IPHVBFIZXIPQ UPM NTZ QFI IUYI TN AYI NTZ QFI TBIZUQTZ. VQ VY UP IGIHQZT-XIHFUPVHUG XUHFVPI ZIYIXLGVPJ U QEBIDZVQIZ, DVQF U BGAJLTUZM QT YDUB GIQQIZY, ZTQTZY QT NAZQFIZ YHZUXLGI QFI UGBFULIQ UPM U GUXB BUPIG QT MVYBGUE QFI ZIYAGQ. XTYQ XTMIGY TN IPVJXU AYIM 3 TZ 4 ZTQTZY DVQF U ZINGIHQTZ QT UGGTD QFI YUXI YIQQVPJY QT LI AYIM NTZ IPHVBFIZVPJ UPM MIHVBFIZVPJ")
print (gs.translate(decriptar(chave,"QFI IPVJXU HVBFIZ XUHFVPI DUY VPSIPQIM LE U JIZXUP IPJVPIIZ, UZQFAZ YHFIZLVAY, DFT UBBGVIM NTZ FVY BUQIPQ TP NILZAUZE 23, 1918. QFVY DUY VP QFI YUXI QVXI NZUXI QFUQ 3 TQFIZ VPSIPQTZY NZTX 3 TQFIZ HTAPQZVIY UGYT UBBGVIM NTZ U BUQIPQ NTZ U ZTQUZE HVBFIZ XUHFVPI. YHFIZLVAY NVZYQ QZVIM QT YIGG FVY MIYVJP QT QFI JIZXUP XVGVQUZE LAQ NVPMVPJ PT VPQIZIYQ MIHVMIM QT YQUZQ AB FVY TDP HTXBUPE QT XUPANUHQAZI QFI IPVJXU NTZ HTXXIZHVUG YUGI. QFI IPVJXU XUHFVPI DUY NVZYQ TNNIZIM NTZ YUGI VP 1923, LAQ FUM NID QUWIZY. QFI IPVJXU XUHFVPI DUY UP VPJIPVTAY UMSUPHI VP QIHFPTGTJE, LTQF NTZ QFI YQZIPJQF TN QFI IPHVBFIZXIPQ UPM NTZ QFI IUYI TN AYI NTZ QFI TBIZUQTZ. VQ VY UP IGIHQZT-XIHFUPVHUG XUHFVPI ZIYIXLGVPJ U QEBIDZVQIZ, DVQF U BGAJLTUZM QT YDUB GIQQIZY, ZTQTZY QT NAZQFIZ YHZUXLGI QFI UGBFULIQ UPM U GUXB BUPIG QT MVYBGUE QFI ZIYAGQ. XTYQ XTMIGY TN IPVJXU AYIM 3 TZ 4 ZTQTZY DVQF U ZINGIHQTZ QT UGGTD QFI YUXI YIQQVPJY QT LI AYIM NTZ IPHVBFIZVPJ UPM MIHVBFIZVPJ"), 'pt-br'))
